name: "Validate devcontainer-feature.json files"
on:
  workflow_dispatch:
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: "Run Python script: bump"
        run: |
          set -e
          echo "Start."
          python -m pip install -r workflows/bump/requirements.txt
          python workflows/bump/main.py

#      - name: "Validate devcontainer-feature.json files"
#        uses: devcontainers/action@v1
#        with:
#          validate-only: "true"
#          base-path-to-features: "./src"
